pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    stages {
        stage('initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Git SCM') {
            steps {
                git branch: 'master', url: 'https://github.com/royalt1234/Jenkins-Sonarqube-Artifactory-Php.git'
            }
        }

        stage('prepare ansible for execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" "${WORKSPACE}/deploy/ansible.cfg"'
            }
        }

        stage('run ansible playbook') {
            steps {
                ansiblePlaybook become: true, colorized: true, credentialsId: 'ssh-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
            }
        }

        stage('cleanup') {
            steps {
                cleanWs()
            }
        }
    }
}