pipeline {
    agent any

    stages {
        stage('test') {
            step {
                script {
                    sh 'echo "testing stage"'
                }
            }
        }

        stage('build') {
            step {
                script {
                    sh 'echo "building stage"'
                }
            }
        }

        stage('deploy') {
            step {
                script {
                    sh 'echo "deploying stage"'
                }
            }
        }
    }
}

